### ISSUE TITLE
MetaMask Android App Shows High Balance After Sync for Migration

### ISSUE THREAD

**Issue by EdPantal** [yam-finance/yam-migration#1]
@brockelmore  My MetaMask shows a very high YAMv2 balance. My desktop browser extension correctly shows 4.852 YAMv2. It's probably a MetaMask issue but it's very disturbing. Thanks. Ed
![Screenshot_20200820-153118_MetaMask](https://user-images.githubusercontent.com/25556145/90817891-3a8a4e80-e2fc-11ea-880d-b2f2127953a5.jpg)

**Comment by brockelmore** [comment]
thanks, i'll file an issue w/ metamask. they clearly dont actually check the number of decimals a token has.

**Comment by EdPantal** [comment]
I just created a MetaMask ticket too.

**Comment by EdPantal** [comment]
#1789

**Comment by EdPantal** [comment]
Hi Brock.
Can you check my ticket with MetaMask?
https://github.com/MetaMask/metamask-mobile/issues/1789

Thanks.
Ed

cointracker.io

[image: image.png]

**Comment by EdPantal** [comment]
@brockelmore My coin tracker sees this transaction. Please check.
https://etherscan.io/tx/0xf2d8e3a00eb4b45c4b1578b11d90bc52fc55f2e3336b96b669f1afdc344dc30d

Please help. If this is correct it means I don't have to work tonight.

![image](https://user-images.githubusercontent.com/25556145/90955908-cbbe0a00-e44f-11ea-9045-6dbd7ad91073.png)

**Comment by EdPantal** [comment]
@brockelmore Looking at the top holders, the award decimal seems off six places.

**Comment by EdPantal** [comment]
@brockelmore Etherscan shows 18 decimals but it should be 24.
I see the note. You can close this ticket.
"Note: The YamV2 contract uses an un-common 24 decimals which currently affects the token amount we display on Etherscan. We currently display this as 18 decimals only"
